-- Migration number: 0002 	 2026-09-07T12:02:00.000Z

-- Sample agencies + users, carried over from the old counsellor_performance seed
-- data (tmp/sample-excel-sheets/*.xlsx, May-Aug 2026). The old
-- counsellor_performance INSERT block is dropped -- that table no longer exists.
-- Person-matching / assignment-period rules used to build this data are
-- documented in git history (see the original 0002_seed_sample_performance_data.sql).

INSERT INTO agencies (name) VALUES
  ('AM2PM'),
  ('SKS Enterprises');

INSERT INTO users (id, name, email, doj, team_id, agency_id, is_active, person_id) VALUES
  (1, 'Ritika Dakolia', 'c-ritika.dakolia@bennett.edu.in', '2025-11-24', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 1),
  (2, 'Mishika Jindal', 'c-mishika.jinddal@bennett.edu.in', '2026-01-12', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 2),
  (3, 'Vishwadeep Saxena', 'cc-vishwadeep.saxena@bennett.edu.in', '2026-04-01', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 3),
  (4, 'Md.Arshad Hussain', 'c-arshad.hussain@bennett.edu.in', '2024-03-01', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 4),
  (5, 'Prachi Mehta', 'c-prachi.mehta@bennett.edu.in', '2026-03-18', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 5),
  (6, 'Abhishek Kumar Singh', 'c-abhishek.singh@bennett.edu.in', '2026-03-25', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 6),
  (7, 'Amrit Raj Verma', 'c-amrit.verma@bennett.edu.in', '2025-11-24', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 7),
  (8, 'Akshat Sharma', 'c-akshat.sharma@bennett.edu.in', '2025-12-29', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 8),
  (9, 'Shweta Gupta', 'c-shweta.gupta@bennett.edu.in', '2026-01-12', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 9),
  (10, 'Simran Jaiswal', NULL, NULL, (SELECT id FROM teams WHERE name = 'Engineering'), NULL, 1, 10),
  (11, 'Durgesh Tiwari', 'c-durgesh.tiwari@bennett.edu.in', '2026-03-16', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 11),
  (12, 'Swati Shandaliya', 'c-swati.shandaliya@bennett.edu.in', '2025-12-15', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 12),
  (13, 'Karandeep Singh', NULL, NULL, (SELECT id FROM teams WHERE name = 'Engineering'), NULL, 1, 13),
  (14, 'Preeti Singh', 'c-preeti.singh@bennett.edu.in', '2026-01-15', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 14),
  (15, 'Hans Sharma', 'c-hans.sharma@bennett.edu.in', '2026-02-27', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 15),
  (16, 'Dev Gautam', NULL, NULL, (SELECT id FROM teams WHERE name = 'Engineering'), NULL, 1, 16),
  (17, 'Surbhi Sharma', NULL, NULL, (SELECT id FROM teams WHERE name = 'Engineering'), NULL, 1, 17),
  (18, 'Tanushree Baisala', 'c-tanushree.bansal@bennett.edu.in', '2025-12-15', (SELECT id FROM teams WHERE name = 'Management'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 18),
  (19, 'Shalini Panjiyar', 'c-shalini.paniyar@bennett.edu.in', '2025-12-15', (SELECT id FROM teams WHERE name = 'Management'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 19),
  (20, 'Abhinav Kumar', 'c-abhinav.kumar@bennett.edu.in', '2026-03-23', (SELECT id FROM teams WHERE name = 'Management'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 20),
  (21, 'Arvind Kumar', 'c-arvind.kumar@bennett.edu.in', '2026-04-13', (SELECT id FROM teams WHERE name = 'Management'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 21),
  (22, 'Sumitra Bharti', 'c-sumitra.bharti@bennett.edu.in', '2025-11-24', (SELECT id FROM teams WHERE name = 'Law'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 0, 22),
  (23, 'Sumitra Bharti', 'c-sumitra.bharti@bennett.edu.in', '2025-11-24', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 22),
  (24, 'Mihir Kumar', 'c-mihir.kumar@bennett.edu.in', '2025-11-01', (SELECT id FROM teams WHERE name = 'Law'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 24),
  (25, 'Debjani Saha', 'c-debanjani.saha@bennett.edu.in', '2026-03-09', (SELECT id FROM teams WHERE name = 'Law'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 25),
  (26, 'Ashutosh Pandey', 'c-ashutosh.pandey@bennett.edu.in', '2025-12-29', (SELECT id FROM teams WHERE name = 'Media/Liberal Arts'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 26),
  (27, 'Shraddha Sharma', 'c-shraddha.sharma@bennett.edu.in', '2026-02-12', (SELECT id FROM teams WHERE name = 'Media/Liberal Arts'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 27),
  (28, 'Taniya Adhikari', 'c-tanya.adhikari@bennett.edu.in', '2025-12-29', (SELECT id FROM teams WHERE name = 'Media/Liberal Arts'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 28),
  (29, 'Deepanshi Sharma', 'c-deepanshi.sharma@bennett.edu.in', '2025-12-22', (SELECT id FROM teams WHERE name = 'Design'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 29),
  (30, 'Nidhi Khandelwal', 'c-nidhi.khandelwal@bennett.edu.in', '2026-03-16', (SELECT id FROM teams WHERE name = 'Design'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 30),
  (31, 'Deepali Gupta', 'c-deepali.gupta@bennett.edu.in', '2025-02-17', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 31),
  (32, 'Safiya Farheen', 'c-safiya.farheen@bennett.edu.in', '2026-03-09', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 32),
  (33, 'Anshika Garg', 'c-anshika.garg@bennett.edu.in', '2026-03-31', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 33),
  (34, 'Shalini Kumari', 'c-shalini.kumari@bennett.edu.in', '2025-12-29', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 34),
  (35, 'Sukriti Shukla', 'c-sukriti.shukla@bennett.edu.in', '2026-04-13', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 35),
  (36, 'Ankita Yadav', 'c-ankita.yadav@bennett.edu.in', '2026-03-30', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 36),
  (37, 'Sarang Patel', 'c-sarang.patel@bennett.edu.in', '2026-02-27', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 37),
  (38, 'Vansh Aggarwal', 'c-vansh.aggarwal@bennett.edu.in', '2026-04-28', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 38),
  (39, 'Bhoomi Kanujiya', 'c-bhoomi.kanujiya@bennett.edu.in', '2026-03-18', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 39),
  (40, 'Sakaar Srivastava', 'c-sakaar.srivastava@bennett.edu.in', '2026-05-05', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 40),
  (41, 'Archi Singh', NULL, NULL, (SELECT id FROM teams WHERE name = 'Inbound'), NULL, 1, 41),
  (42, 'Adiba Farid', 'c-abida.farid@bennett.edu.in', '2026-03-09', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 42),
  (43, 'Yashika Gupta', 'c-yashika.gupta@bennett.edu.in', '2026-05-05', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 43),
  (44, 'Ayushi Aggarwal', 'c-ayushi.aggarwal@bennett.edu.in', '2026-05-13', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 44),
  (45, 'Akanksha Sengar', 'c-akanksha.sengar@bennett.edu.in', '2026-05-05', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 45),
  (46, 'Agrim Chaudhary', 'c-agrim.chaudhary@bennett.edu.in', '2025-12-22', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 46),
  (47, 'Harsh Vardhan', 'c-harsh.vardhan@bennett.edu.in', '2026-05-20', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 47),
  (48, 'Sneha Gupta', 'c-sneha.gupta@bennett.edu.in', '2026-05-25', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 48),
  (49, 'Deepali Yadav', 'c-deepali.yadav@bennett.edu.in', '2026-04-13', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 49),
  (50, 'Vikas Pal', 'c-vikas.pal@bennett.edu.in', '2026-04-13', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 50),
  (51, 'Aashutosh Shah', 'c-aashutosh.shah@bennett.edu.in', '2026-04-13', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 51),
  (52, 'Roshan Kumar Singh', 'c-roshan.singh@bennett.edu.in', '2026-04-13', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 52),
  (53, 'Sneha Kumari', 'c-sneha.kumarri@bennett.edu.in', '2026-04-14', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 53),
  (54, 'Palki Mittal', 'c-palki.mittal@bennett.edu.in', '2026-04-17', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 54),
  (55, 'Ishika Singh', 'c-ishika.singh@bennett.edu.in', '2026-04-16', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 55),
  (56, 'Yogita Singh', 'c-yogita.singh@bennett.edu.in', '2026-04-14', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 56),
  (57, 'Surbhi Yadav', 'c-surbhi.yadav@bennett.edu.in', '2026-04-20', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 57),
  (58, 'Sakshi Singh', 'c-sakshi.singh@bennett.edu.in', '2026-04-16', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 58),
  (59, 'Sneha Garg', 'c-sneha.garg@bennett.edu.in', '2026-06-07', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 59),
  (60, 'Supriya Singh', 'c-supriya.singh@bennett.edu.in', '2026-04-13', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 60),
  (61, 'Sanjay Rawat', 'c-sanjay.rawat@bennett.edu.in', '2026-04-09', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 61),
  (62, 'Sanjana Pal', 'c-sanjana.pal@bennett.edu.in', '2026-04-20', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 62),
  (63, 'Ritu Raj', 'c-ritu.raj@bennett.edu.in', '2026-04-09', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 63),
  (64, 'Mushraff Ali', 'c-mushraff.ali@bennett.edu.in', '2026-04-06', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 64),
  (65, 'Harshit Kumar', 'c-harshit.kumar@bennett.edu.in', '2026-04-09', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 65),
  (66, 'Pragati Kala', 'c-pragati.kala@bennett.edu.in', '2026-04-16', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 66),
  (67, 'Bhavna Sahu', 'c-bhavna.sahu@bennett.edu.in', '2026-04-16', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 67),
  (68, 'Pallavi Singh', 'c-pallavi.singh@bennett.edu.in', '2026-04-13', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 68),
  (69, 'Rishabh Sharma', 'c-rishabh.sharma@bennett.edu.in', '2026-04-14', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 69),
  (70, 'Abhinav Teotia', 'c-abhinav.teotia@bennett.edu.in', '2026-04-17', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 70),
  (71, 'Shivansh Tyagi', 'c-shivansh.tyagi@bennett.edu.in', '2026-04-13', (SELECT id FROM teams WHERE name = 'Management'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 71),
  (72, 'Nikhil Pal', 'c-nikhil.pal@bennett.edu.in', '2026-05-11', (SELECT id FROM teams WHERE name = 'Management'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 72),
  (73, 'Ashna Sidiqqui', 'c-ashna.sidiqqui@bennett.edu.in', '2026-04-16', (SELECT id FROM teams WHERE name = 'Management'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 73),
  (74, 'Tanya Yadav', 'c-tanya.yadav@bennett.edu.in', '2026-04-16', (SELECT id FROM teams WHERE name = 'Management'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 74),
  (75, 'Shubham Kumar', 'c-shubham.kumar@bennett.edu.in', '2026-04-06', (SELECT id FROM teams WHERE name = 'Management'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 75),
  (76, 'Bhumika Kumari', 'c-bhumika.kumari@bennett.edu.in', '2026-04-06', (SELECT id FROM teams WHERE name = 'Management'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 76),
  (77, 'Prajukta Kashyap', 'c-prajukta.kashyap@bennett.edu.in', '2026-04-09', (SELECT id FROM teams WHERE name = 'Media/Liberal Arts'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 77),
  (78, 'Abquari Akhtar', 'c-abquar.akhtar@bennett.edu.in', '2026-04-06', (SELECT id FROM teams WHERE name = 'Media/Liberal Arts'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 78),
  (79, 'Karnika Sharma', 'c-karnika.sharma@bennett.edu.in', '2026-04-07', (SELECT id FROM teams WHERE name = 'Law'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 0, 79),
  (80, 'Karnika Sharma', 'c-karnika.sharma@bennett.edu.in', '2026-04-07', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 79),
  (81, 'Himanshu Shahi', 'c-himanshu.shahi@bennett.edu.in', '2026-03-30', (SELECT id FROM teams WHERE name = 'Law'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 81),
  (82, 'Ankita Singh', 'c-ankita.singh1@bennett.edu.in', '2026-04-06', (SELECT id FROM teams WHERE name = 'Design'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 82),
  (83, 'Nayanika Singh', 'c-nayanika.singh@bennett.edu.in', '2026-04-16', (SELECT id FROM teams WHERE name = 'Design'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 0, 83),
  (84, 'Nayanika Singh', 'c-nayanika.singh@bennett.edu.in', '2026-04-16', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 83),
  (85, 'Alok Raj', 'c-alok.raj@bennett.edu.in', '2026-02-02', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 85),
  (86, 'Sonal Singh', 'c-sonal.singh@bennett.edu.in', '2026-04-14', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 86),
  (87, 'Riya Singh', 'c-riya.singh@bennett.edu.in', '2026-04-29', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 87),
  (88, 'Bhumika Kohli', 'c-bhumika.kohli@bennett.edu.in', '2026-05-05', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 0, 88),
  (89, 'Bhumika Kohli', 'c-bhumika.kohli@bennett.edu.in', '2026-05-05', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 88),
  (90, 'Yash Chaudhary', 'c-yash.chaudhary@bennett.edu.in', '2026-06-02', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 90),
  (91, 'Mayank', 'c-mayank@bennett.edu.in', '2026-05-11', (SELECT id FROM teams WHERE name = 'Inbound'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 0, 91),
  (92, 'Mayank', 'c-mayank@bennett.edu.in', '2026-05-11', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 91),
  (93, 'Manisha Gupta', 'c-manisha.gupta@bennett.edu.in', '2026-06-08', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 93),
  (94, 'Aditya Godiyal', 'c-aditya.godiyal@bennett.edu.in', '2026-06-08', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 94),
  (95, 'Vaishnavi', 'c-vaisnavi@bennett.edu.in', '2026-06-01', (SELECT id FROM teams WHERE name = 'Engineering'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 95),
  (96, 'Hemant Singh', 'c-hemant.singh@bennett.edu.in', '2026-06-08', (SELECT id FROM teams WHERE name = 'Management'), (SELECT id FROM agencies WHERE name = 'AM2PM'), 1, 96),
  (97, 'Bashar Nasir', 'c-bashar.nasir@bennett.edu.in', '2026-07-15', (SELECT id FROM teams WHERE name = 'Management'), (SELECT id FROM agencies WHERE name = 'SKS Enterprises'), 1, 97);

