/**
 * Renders migrations/0002_seed_users.sql from scripts/seed/users.json.
 *
 * Every seeded user gets the same default password (DEFAULT_PASSWORD below),
 * hashed here per user with a fresh random salt in the exact format
 * src/lib/auth/password.ts verifies -- so no hash is ever pasted by hand and
 * two users never share a digest. `password_changed_at` is left NULL, which
 * the app reads as "must change password on first login".
 *
 * Team and role ids match migrations/0001_seed_teams_roles.sql. Agencies are
 * created here as well, in AGENCIES order, and `agency` in the JSON is the
 * agency's name (or null). The Meritto dump carries no agency field; the
 * values come from the "Agency Name" column of the monthly performance
 * workbooks (tmp/backfill/apply-agencies.mjs).
 *
 * Usage: node scripts/seed-users.mjs
 */
import fs from "node:fs";
import { webcrypto } from "node:crypto";

const DEFAULT_PASSWORD = "change-it";
const ROSTER_PATH = "scripts/seed/users.json";
const OUT_PATH = "migrations/0002_seed_users.sql";

const TEAMS = { Design: 1, Engineering: 2, Inbound: 3, Law: 4, Management: 5, "Media/Liberal Arts": 6 };
const ROLES = { counsellor: 1, team_leader: 2, mis_executive: 3, admin: 4 };
// Insert order is the id: AM2PM = 1, SKS Enterprises = 2.
const AGENCIES = ["AM2PM", "SKS Enterprises"];
const agencyId = (name) => {
    if (name === null) return null;
    const index = AGENCIES.indexOf(name);
    if (index === -1) throw new Error(`unknown agency ${String(name)}`);
    return index + 1;
};

// Mirrors src/lib/auth/password.ts exactly.
const ALGORITHM = "pbkdf2-sha256";
const ITERATIONS = 100_000;

async function hashPassword(password) {
    const salt = webcrypto.getRandomValues(new Uint8Array(16));
    const key = await webcrypto.subtle.importKey("raw", new TextEncoder().encode(password), "PBKDF2", false, ["deriveBits"]);
    const bits = await webcrypto.subtle.deriveBits({ name: "PBKDF2", hash: "SHA-256", salt, iterations: ITERATIONS }, key, 256);
    const b64 = (bytes) => Buffer.from(bytes).toString("base64");
    return `${ALGORITHM}$${String(ITERATIONS)}$${b64(salt)}$${b64(new Uint8Array(bits))}`;
}

const quote = (value) => `'${String(value).replace(/'/g, "''")}'`;
const nullable = (value) => (value === null ? "NULL" : String(value));

async function main() {
    const roster = JSON.parse(fs.readFileSync(ROSTER_PATH, "utf8"));

    for (const user of roster) {
        if (!(user.role in ROLES)) throw new Error(`${user.name}: unknown role ${user.role}`);
        if (user.team !== null && !(user.team in TEAMS)) throw new Error(`${user.name}: unknown team ${user.team}`);
        if (user.role === "counsellor" && user.merittoUserId === null) throw new Error(`${user.name}: counsellor without Meritto id`);
        if ((user.role === "counsellor" || user.role === "team_leader") && user.team === null) {
            throw new Error(`${user.name}: ${user.role} without a team`);
        }
    }

    const counts = {};
    for (const user of roster) counts[user.role] = (counts[user.role] ?? 0) + 1;

    const out = [];
    out.push(`-- Migration number: 0002 \t ${new Date().toISOString()}`);
    out.push("");
    out.push("-- GENERATED by scripts/seed-users.mjs from scripts/seed/users.json -- edit");
    out.push("-- the JSON and re-run the script rather than this file.");
    out.push("--");
    out.push("-- The counsellor roster comes from the Meritto user dump (numeric Meritto");
    out.push("-- user id, @bennett.edu.in email, non-empty `teams`), minus leadership");
    out.push("-- accounts that carry no targets. team_id is Meritto's team label minus the");
    out.push("-- trailing \" Team\", which maps 1:1 onto the teams in 0001; users listed under");
    out.push("-- several teams take the first canonical one.");
    out.push("--");
    out.push(`-- ${Object.entries(counts).map(([role, n]) => `${String(n)} ${role}`).join(", ")}.`);
    out.push("--");
    out.push(`-- Every user starts with the same default password and password_changed_at`);
    out.push("-- NULL, so the app forces a change on first login. Each hash carries its own");
    out.push("-- random salt (src/lib/auth/password.ts).");
    out.push("--");
    out.push("-- agency_id comes from the \"Agency Name\" column of the monthly performance");
    out.push("-- workbooks (the Meritto dump carries no agency field); users the workbooks");
    out.push("-- never list keep NULL and get assigned through the roster UI.");
    out.push("");
    out.push("INSERT INTO agencies (name) VALUES");
    out.push(AGENCIES.map((name) => `  (${quote(name)})`).join(",\n") + ";");
    out.push("");
    out.push("INSERT INTO users (id, name, email, meritto_user_id, role_id, team_id, agency_id, is_active, password_hash, password_changed_at) VALUES");

    const rows = [];
    for (const user of roster) {
        const hash = await hashPassword(DEFAULT_PASSWORD);
        rows.push(
            `  (${String(user.id)}, ${quote(user.name)}, ${quote(user.email)}, ${nullable(user.merittoUserId)}, ` +
                `${String(ROLES[user.role])}, ${nullable(user.team === null ? null : TEAMS[user.team])}, ` +
                `${nullable(agencyId(user.agency))}, 1, ${quote(hash)}, NULL)`,
        );
    }
    out.push(rows.join(",\n") + ";");
    out.push("");
    out.push("-- Initial assignments go into the changelog too, so a user's history starts");
    out.push("-- at their seed row rather than at their first change. changed_by is NULL");
    out.push("-- (a migration, not a person).");
    out.push("INSERT INTO user_changes (user_id, field, old_value, new_value, changed_by) VALUES");
    const changes = [];
    for (const user of roster) {
        changes.push(`  (${String(user.id)}, 'role_id', NULL, ${String(ROLES[user.role])}, NULL)`);
        if (user.team !== null) changes.push(`  (${String(user.id)}, 'team_id', NULL, ${String(TEAMS[user.team])}, NULL)`);
        if (user.agency !== null) changes.push(`  (${String(user.id)}, 'agency_id', NULL, ${String(agencyId(user.agency))}, NULL)`);
    }
    out.push(changes.join(",\n") + ";");
    out.push("");

    fs.writeFileSync(OUT_PATH, out.join("\n"));
    console.log(`${OUT_PATH}: ${String(roster.length)} users`);
}

await main();
